
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import Header from '@/components/Header';
import ToolCard from '@/components/ToolCard';
import { Tool } from '@/lib/types';

// Export tools array so it can be used in other components
export const tools: Tool[] = [
  {
    id: 'plagiarism-checker',
    name: 'Plagiarism Checker',
    description: 'Verify the originality of your content with our eco-friendly plagiarism detection tool.',
    icon: '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M10 22H5a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v14"/><path d="M7 7h10"/><path d="M7 11h10"/><path d="M7 15h2"/><path d="m16.5 19.5 2.5 2.5 4-4"/></svg>',
    bgColor: 'bg-blue-600',
    route: 'plagiarism-checker'
  },
  {
    id: 'reverse-image-search',
    name: 'Reverse Image Search',
    description: 'Find the original source of images instantly with our powerful image recognition.',
    icon: '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="18" height="18" x="3" y="3" rx="2" ry="2"/><circle cx="9" cy="9" r="2"/><path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21"/></svg>',
    bgColor: 'bg-purple-600',
    route: 'reverse-image-search'
  },
  {
    id: 'video-downloader',
    name: 'Video Downloader',
    description: 'Download videos from popular platforms in the highest quality available.',
    icon: '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>',
    bgColor: 'bg-red-600',
    route: 'video-downloader'
  },
  {
    id: 'paraphrasing-tool',
    name: 'Paraphrasing Tool',
    description: 'Rewrite content to make it unique while maintaining the original meaning.',
    icon: '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M17 22h-1a4 4 0 0 1-4-4V6a4 4 0 0 1 4-4h1"/><path d="M7 22h1a4 4 0 0 0 4-4v-1"/><path d="M7 2h1a4 4 0 0 1 4 4v1"/></svg>',
    bgColor: 'bg-amber-600',
    route: 'paraphrasing-tool'
  },
  {
    id: 'ai-detector',
    name: 'AI Detector',
    description: 'Determine if content was generated by AI or written by a human.',
    icon: '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2H2v10l9.29 9.29c.94.94 2.48.94 3.42 0l6.58-6.58c.94-.94.94-2.48 0-3.42L12 2Z"/><path d="M7 7h.01"/></svg>',
    bgColor: 'bg-indigo-600',
    route: 'ai-detector'
  },
  {
    id: 'grammar-checker',
    name: 'Grammar Checker',
    description: 'Improve your writing with our advanced grammar and spelling correction.',
    icon: '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M8 21h12a2 2 0 0 0 2-2v-2H10v2a2 2 0 1 1-4 0V5a2 2 0 1 0-4 0v3h4"/><path d="M19 15V5a2 2 0 0 0-2-2H4"/></svg>',
    bgColor: 'bg-green-600',
    route: 'grammar-checker'
  }
];

const Index = () => {
  const [isVisible, setIsVisible] = useState(false);
  
  // Simulate loading effect
  setTimeout(() => setIsVisible(true), 100);

  return (
    <div className="min-h-screen bg-gradient-to-b from-white to-gray-50 dark:from-gray-900 dark:to-black text-foreground">
      <Header />
      
      <main className="pt-32 pb-20 px-4">
        <section className="max-w-7xl mx-auto text-center mb-20">
          <div className={`transition-all duration-700 ${isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}`}>
            <div className="inline-block px-3 py-1 rounded-full bg-primary/10 text-primary text-sm font-medium mb-4">
              Ethical & Eco-Friendly Tools
            </div>
            <h1 className="text-4xl md:text-6xl font-bold mb-6 tracking-tight">
              All-in-one Content Tools <br className="hidden md:block" />
              <span className="text-primary">for Creators</span>
            </h1>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto mb-8">
              Supercharge your content creation process with our suite of powerful, 
              energy-efficient tools designed for modern creators.
            </p>
            
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Button asChild size="lg" className="text-base py-6">
                <Link to="/tools">
                  Explore All Tools
                </Link>
              </Button>
              <Button asChild variant="outline" size="lg" className="text-base py-6">
                <a href="#features">
                  How It Works
                </a>
              </Button>
            </div>
          </div>
        </section>
        
        <section className="max-w-7xl mx-auto mb-20">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold mb-4">Discover Our Tools</h2>
            <p className="text-muted-foreground max-w-xl mx-auto">
              Our carefully crafted suite of tools to help you create, optimize, and verify your content.
            </p>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {tools.map((tool, index) => (
              <ToolCard 
                key={tool.id} 
                tool={tool} 
                index={index}
              />
            ))}
          </div>
        </section>
        
        <section id="features" className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold mb-4">Why Choose EcoTools</h2>
            <p className="text-muted-foreground max-w-xl mx-auto">
              Our commitment to providing powerful tools while minimizing environmental impact.
            </p>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="glass-panel p-6 text-center">
              <div className="w-12 h-12 rounded-full bg-green-100 dark:bg-green-900 flex items-center justify-center mx-auto mb-4">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-green-600">
                  <path d="M12 22c5.523 0 10-4.477 10-10S17.523 2 12 2 2 6.477 2 12s4.477 10 10 10z"/>
                  <path d="M14.31 8.31a4 4 0 0 1 0 5.66"/>
                  <path d="M8.31 14.31a4 4 0 0 1 0-5.66"/>
                </svg>
              </div>
              <h3 className="text-xl font-medium mb-2">Energy Efficient</h3>
              <p className="text-muted-foreground text-sm">
                Our tools are optimized to use minimal computing resources, reducing carbon footprint.
              </p>
            </div>
            
            <div className="glass-panel p-6 text-center">
              <div className="w-12 h-12 rounded-full bg-blue-100 dark:bg-blue-900 flex items-center justify-center mx-auto mb-4">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-blue-600">
                  <rect width="18" height="11" x="3" y="11" rx="2" ry="2"/>
                  <path d="M7 11V7a5 5 0 0 1 10 0v4"/>
                </svg>
              </div>
              <h3 className="text-xl font-medium mb-2">Privacy Focused</h3>
              <p className="text-muted-foreground text-sm">
                Your content is never stored or used for training AI models, ensuring complete privacy.
              </p>
            </div>
            
            <div className="glass-panel p-6 text-center">
              <div className="w-12 h-12 rounded-full bg-purple-100 dark:bg-purple-900 flex items-center justify-center mx-auto mb-4">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-purple-600">
                  <path d="M8.8 20v-4.1l1.9.2a2.3 2.3 0 0 0 2.164-2.1V8.3A5.37 5.37 0 0 0 2 8.25c0 2.8.656 3.95 1 4.75"/>
                  <path d="M19.8 17.817a5.364 5.364 0 0 0-3.1-3.45"/>
                  <path d="M22 20v-4.1l-1.9.2a2.3 2.3 0 0 1-2.064-2"/>
                  <path d="M15.54 15H18a2 2 0 0 1 2 2v3"/>
                </svg>
              </div>
              <h3 className="text-xl font-medium mb-2">Accessible to All</h3>
              <p className="text-muted-foreground text-sm">
                Designed to be inclusive and accessible to everyone, regardless of technical background.
              </p>
            </div>
          </div>
        </section>
      </main>
      
      <footer className="bg-white dark:bg-black border-t py-12 px-4">
        <div className="max-w-7xl mx-auto">
          <div className="flex flex-col md:flex-row justify-between items-center">
            <div className="mb-6 md:mb-0">
              <Link to="/" className="flex items-center space-x-2">
                <div className="w-8 h-8 rounded-md bg-primary flex items-center justify-center">
                  <svg viewBox="0 0 24 24" className="w-5 h-5 text-primary-foreground" fill="none" stroke="currentColor" strokeWidth="2">
                    <path d="M12 3v3m0 4.5v3m0 4.5v3M3 12h3m4.5 0h3m4.5 0h3" />
                  </svg>
                </div>
                <span className="font-medium text-lg">EcoTools</span>
              </Link>
              <p className="text-sm text-muted-foreground mt-2 max-w-xs">
                Eco-friendly content tools for creators, built with sustainability in mind.
              </p>
            </div>
            
            <div className="grid grid-cols-2 gap-8 sm:grid-cols-3">
              <div>
                <h3 className="text-sm font-medium mb-3">Tools</h3>
                <ul className="space-y-2">
                  {tools.slice(0, 3).map(tool => (
                    <li key={tool.id}>
                      <Link 
                        to={`/tools/${tool.route}`}
                        className="text-sm text-muted-foreground hover:text-foreground transition-colors"
                      >
                        {tool.name}
                      </Link>
                    </li>
                  ))}
                </ul>
              </div>
              
              <div>
                <h3 className="text-sm font-medium mb-3">More Tools</h3>
                <ul className="space-y-2">
                  {tools.slice(3).map(tool => (
                    <li key={tool.id}>
                      <Link 
                        to={`/tools/${tool.route}`}
                        className="text-sm text-muted-foreground hover:text-foreground transition-colors"
                      >
                        {tool.name}
                      </Link>
                    </li>
                  ))}
                </ul>
              </div>
              
              <div>
                <h3 className="text-sm font-medium mb-3">Company</h3>
                <ul className="space-y-2">
                  <li>
                    <Link 
                      to="/about"
                      className="text-sm text-muted-foreground hover:text-foreground transition-colors"
                    >
                      About Us
                    </Link>
                  </li>
                  <li>
                    <Link 
                      to="/privacy"
                      className="text-sm text-muted-foreground hover:text-foreground transition-colors"
                    >
                      Privacy Policy
                    </Link>
                  </li>
                  <li>
                    <Link 
                      to="/terms"
                      className="text-sm text-muted-foreground hover:text-foreground transition-colors"
                    >
                      Terms of Service
                    </Link>
                  </li>
                </ul>
              </div>
            </div>
          </div>
          
          <div className="border-t mt-12 pt-8 flex flex-col md:flex-row justify-between items-center">
            <p className="text-sm text-muted-foreground">
              © {new Date().getFullYear()} EcoTools. All rights reserved.
            </p>
            
            <div className="flex space-x-6 mt-4 md:mt-0">
              <a 
                href="#" 
                className="text-muted-foreground hover:text-foreground transition-colors"
                aria-label="Twitter"
              >
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z"/>
                </svg>
              </a>
              <a 
                href="#" 
                className="text-muted-foreground hover:text-foreground transition-colors"
                aria-label="GitHub"
              >
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4"/>
                  <path d="M9 18c-4.51 2-5-2-7-2"/>
                </svg>
              </a>
              <a 
                href="#" 
                className="text-muted-foreground hover:text-foreground transition-colors"
                aria-label="LinkedIn"
              >
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z"/>
                  <rect width="4" height="12" x="2" y="9"/>
                  <circle cx="4" cy="4" r="2"/>
                </svg>
              </a>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default Index;
