// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iseawalxbnkgjpviulrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzZWF3YWx4Ym5rZ2pwdml1bHJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NTQ4NTgsImV4cCI6MjA2NDAzMDg1OH0.hRkYsP2Y5FQ-GcbN18Pz0biB-9wzyalbSk44AwB3ilY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);